server:
  port: 9777
spring:
  profiles:
    group:
      local: localdb
      prod: proddb
      dev: devdb

  datasource:
    #    driver-class-name: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@localhost:1521/orcl
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521/ORCL
    username: aki2110
    password: aki2110

  messages:
    basename: errors

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 701027355062-ki713avev3n81qfgi0nms2isjdo6gl30.apps.googleusercontent.com
            client-secret: COKgJXrLK6kdHmhLrGM1waXF
            scope:
              - email
              - profile
          facebook:
            client-id: 319620346522575
            client-secret: 740d6c090612bfd562c29a5ffff1b14b
            scope:
              - email
              - public_profile
          naver:
            client-id: 2VtflNZYgQKk45yA0WfY
            client-secret: 3h6Nh39ngJ
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9777/login/oauth2/code/naver
          kakao:
            client-id: dd9b6b44a1278052828650f6b86f03d1
            #            client-secret: 09XbVusYhLevtAYwUNHVpjRYKsyPcfQN
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9777/login/oauth2/code/kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json 으로 받는데 response 라는 키값으로 네이버가 리턴 해준다.
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: properties

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html






# [ http 로그 ]
#logging:
#  level:
#    org.apache.coyote.http11: debug

#file:
#  dir: C:/akinux/study/file/


---
spring:
  config:
    activate:
      on-profile: localdb
  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521/orcl
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521/ORCL
    username: aki2110
    password: aki2110
#    driver-class-name: oracle.jdbc.driver.OracleDriver - 9버전 이후로 이름 변경됨

---